Sprint 9: controllers-films-users
B10nicle/java-filmorate pull request #3
Opened 2022-10-29 07:28 UTC by B10nicle

Создана основная структура проекта для дальнейших доработок

2022-10-30 10:08 UTC, ErkinKasymaliev requested changes
Олег, привет!
Хорошая работа, но есть куски кода где можно улучшить

2022-10-30 10:08 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +@RequestMapping("/films")
отлично

2022-10-30 10:08 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private final FilmService filmService;
тут смотри как можно делать:
если к полю ты добавил final, то над конструктором уже необязательно ставить @Autowired. И наоборот, если у поля, которое будет инжектиться, нет final, то над конструктором нужен @Autowired. 
Этот коммент просто для ознакомления

2022-10-30 10:08 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmStorage.java
> +    Film addFilm(Film film);
Смотри у тебя здесь и в UserStorage методы по идее одинаковые. Может тебе сделать один интерфейс или один абстрактный класс и его использовать для UserStorage и FilmStorage.
Но попробуй через абстрактный класс

2022-10-30 10:08 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorageImpl.java
> +    public Map<Integer, Film> getFilms() {
Давай здесь будем лучше List<Film> возвращать, что бы в контроллере не делать лишних движений как getFilms.values(); а просто getFilms(). Следовательно в сервисе надо будет тоже List возвращать. Также сделай для InMemoryUserStorageImpl

2022-10-30 10:08 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/validator/film/FilmValidator.java
> +public interface FilmValidator {
Здесь тоже можно один Интерфейс сделать, например
public interface Validator<T> {

      void validate(T t);

}

2022-10-30 10:08 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/service/film/FilmService.java
> +public interface FilmService {
Смотри у тебя здесь и в UserService методы по идее одинаковые. Может тебе сделать один интерфейс или один абстрактный класс и его использовать для UserService и FilmService.
Но попробуй через абстрактный класс

2022-10-30 10:08 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/entity/Film.java
> +    private LocalDate releaseDate;
давай тут как в ТЗ написано попробуем валидационные аннотацию использовать.
Надо будет
1) их добавить
2) добавить в контроллерах @Valid
3) чуть переработать методы validate()

2022-11-02 19:46 UTC, B10nicle commented
Эркин, привет!

Внёс правки согласно твоим комментариям, плюс также:

добавил сваггер на http://localhost:8080/swagger-ui/
добавил метод delete всех фильмов и юзеров
добавил метод get фильмов и юзеров по id
добавил метод delete фильмов и юзеров по id

2022-11-03 06:38 UTC, ErkinKasymaliev approved these changes
Отлично, работа принята!

2022-11-03 08:04 UTC, merged